### ISSUE TITLE
Animation Call #1

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#10]
```meta
Date: 2020-12-21
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2020-12-21 17:00 UTC
```

### Agenda

In our second meeting, we will be taking a look at the storyboard progress and checking some of the early drafts of the scenes. We will still be discussing our storyboard and shape the base for the script.

1. Discussing and brainstorming ideas for the  storyboard https://app.milanote.com/1KEd1q1fovn698/btcpay-animated-video?p=nZfM3RpnrSC 
2. TBD (feel free to suggest in the comments)

### Check your timezone

https://everytimezone.com/s/9f28ebce

### Join the call

https://meet.jit.si/BTCPayAnimationCall

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by Zaxounette** [comment]
BTCPay Server Animation Call: 21/12/2020, 1700 UTC
Participants:
Zaxounette, Webwor, Britttt


* Need to create the file and folder relating to the scripts in the media repository (@Brittttt or @Zaxounette )
* Taking on the last meetings and Kukks's block pop-up idea, Parker shows us new mock-ups. Working from the end-scene backwards, Webwor shows us a sketch of a last scene, revolving around the BTCPay logo pull-out.
Additionally, he shows us an screenshot of said pull-out.

* Switching to script, working on defining the chapters of the script to help make context.
After some discussions, a proposal follows:
SHORT INTRO: Old financial world
CHAPTER 1: No BTCPay to using BTCPay
CHAPTER 2: Becoming a circular economy
EXTRO: Multiple circular economies building up (animated by the pull-out previously shown)

* Discussing and going back and forth on animation ideas:
Webwor wants to make animated people this time. Building on this, we discuss having these people being the introduction of BTCPay to the different recipients (represented by the various BTCPay use-cases: Merchant, tips/donations, tenants/land-lords, etc ...)

**Comment by britttttk** [comment]
Use Case animation ideas:

Here are some features that could be good candidates for animation. They wouldn't necessarily need explicit explanations but some ideas that can be shown in the "circular economy" with btcpay. 

| BTCPay Feature Name  |  Use Case Name  |  Use Case Example  |
|:--:|--|--|
| Pay Button  |  Donations/Tips  | Non-profit donation, social media tips |
| Point of Sale App | Point of Sale | Physical store PoS terminal, E-commerce PoS page |
| Crowdfund App | Crowdfund | Raise money for a disaster or project |
| Payment Request | Pay Me (merchant) | Someone pays to your btcpay |
| Pull Payment | Pay You (freelancer) | Someone pulls payment from your btcpay | 
| Invoices | Manage all invoices | View all invoices, like a bank |
| Wallets | Manage all transactions | View all transactions, like a bank |
| Third Party Host | Setup btcpay for others | Let family/friends accept BTC using your btcpay |

**Comment by Zaxounette** [comment]
> They wouldn't necessarily need explicit explanations but some ideas that can be shown in the "circular economy" with btcpay.

Brainstorming here:
They could also be shown briefly (some of them, all of them might be too long) in short shots in the CHAPTER 1 section, where the animated people make their counterparty become BTCPay users in the process.

**Comment by Zaxounette** [comment]
Brainstorm idea number 2

* The world without BTCPay could be grey, and the animated people (explained above) could be colored.
* When animated people interact with counterpart and said counterpart becomes a BTCPay users, they become colored, and their surroundings also (like their shop or home).
* In EXTRO, the pull-out scene could show the grey color becoming non-dominant and being replaced by BTCPay colors gradually.
