### ISSUE TITLE
Designer Call #6

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/organization#31]
```meta
Date: 2021-04-15
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-04-15 17:00 UTC
```

### Agenda

This meeting should be considered an intermediate meeting between releases.
We will be working on items that @dstrukt and @dennisreimann have on standby, not necessarily related to the next release.

Feel free to comment below to add additional items you would like discussed.

### Check your timezone

https://everytimezone.com/s/5f1cc38b

### Join the call

https://meet.jit.si/IScheduledThisCallSoICallitHoweverIWant

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by dennisreimann** [comment]
Topics from my side:

- Color variables (needed to finish btcpayserver/btcpayserver-design#2)
- API icon for the website (needed to finish btcpayserver/btcpayserver.org#140)
- Payjoin option to hot wallet setup (decide on how to progress in #2450)
- Potential next round of wallet setup finetuning (see #2277 and #2276)

**Comment by dstrukt** [comment]
https://github.com/btcpayserver/btcpayserver/pull/2439 - Some table discussion and UI A/B choices with a bit of context

**Comment by Zaxounette** [comment]
Designer call N°6 notes:
Attendees: @dennisreimann , @dstrukt , @pavlenex , @Zaxounette .

----

**Color variables:**
Color variables relating to the upcoming Bootstrap 5 migration are on track.
Neutral definitions and setting mapping, light/dark and neutral light/dark definitions are good to go.

It is discussed the fact that a pair programmed implementation of the migration between @dennisreimann and @dstrukt might be the best approche because more effective.

As of today, the first colors need defining so that the [Bootstrap 5 migration PR](https://github.com/btcpayserver/btcpayserver-design/pull/2) be completed.

The next release regarding BTCPay Server is expected to be in the next 10 days. It is discussed the fact that the above PR should be merged immediately after the next release to avoid code conflicts. The definitive PR will be presented shortly so as to give the review process sufficient time before the quick merge.

---- 

**API icon:**
Discussions about proper placement in the website.
It is defined that the API should be prominently placed, thus centered in place of the actual `Custom Integrations`, which should itself be displaced.

Is also discussed the need to add a proper link in the website and documentation headers pointing to the API specific documentation, again in the goal of making the API's existence more prominent.

----

**Lightning setup mock-ups:**

Is discussed the full screen layout. Identical as the wallet setup "wizard" introduced in a previous release.
@dstrukt  's explorations around this topic revolve mostly around reducing the amount of noise in the LN setup process and the use of visually prominent CTA items.

Is discussed the possibility of migrating the `toggle CTA` to the main on-chain + LN wallet overview. It is agreed that this is a good exploration to conduct. Emperor @NicolasDorier will be satisfied.

A short discussion occurs about the ordering of the main setup page title and the warning sentence following.
It is also noted that it will be possible to leverage the Bootstrap 5 migration for the visual components of the LN setup page.

The CTA between custom node and internal node is discussed. Multiple visuals are proposed and don't find consensus. A display of options will be shown in the [Mattermost UI/UX channel](https://chat.btcpayserver.org/btcpayserver/channels/ux-ui) for all to give feedback soon™.
[Bootstrap 5 button groups](https://getbootstrap.com/docs/5.0/components/button-group/) are found to be a good for this use-case.

The `Public Node Info` link is finally discussed. It is proposed that it also be migrated to the main wallet overview, for accessibility. Consensus is found on the idea. 
The actual representation of the CTA for this item is still to be defined. Icon ? Text ? Text is chosen as of now, but can be modified later on.

----

**Table discussions regarding the API key display page:**
It should be defined how we handle table decisions and display permissions.

Some discussions occur around possible options, but don't find consensus due to the fact that the attendees might not be the perfect user profil.
Nonetheless, it is said that [Bootstrap 5 popovers](https://getbootstrap.com/docs/5.0/components/popovers/) could be a good solution to displaying the permissions per API key.

For a more in depth exploration, @Kukks 's opinion is needed.

----
