### ISSUE TITLE
Documentation Call #0

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#4]
```meta
Date: 2020-12-02
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2020-12-02 17:00 UTC
```

### Agenda

1. Overview of pull requests and final comments before cleaning up the stalled PR's.
2. Comparing what's been added in [v1.0.6.0](https://github.com/btcpayserver/btcpayserver/pull/2080) and checking if we missed anything
3. Looking through the issues list and closing the outdated ones. 
4. Assigning remaining important issues 

### Check your timezone

LINK FOR TIMEZONE https://everytimezone.com/s/0e565121

### Join the call

https://meet.jit.si/btcpayserverdocumentation

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by pavlenex** [comment]
Anybody, feel free to suggest agenda and add anything you'd like discussed in the comments. I entered a wrong month, so the meeting is on 2nd December, obviously not November 😄

**Comment by Zaxounette** [comment]
Additional items I'd like to discuss in this meeting:

* Looking for consensus on a proposed menu item change. https://github.com/btcpayserver/btcpayserver-doc/issues/769#issuecomment-730471795 
I invite anyone to pitch in, even if not attending the meeting.
* @RiccardoMasutti Seems to have issues resolving conflicting files (rebases and such), resulting in two stalled PR's.
Could be a good idea to get him in the meeting, or provide him support on this matter before-hand.

**Comment by pavlenex** [comment]
Thanks everyone for joining the first public documentation meeting. 
We cleared out some staled pull requests and issues and assigned few existing ones. Reviewed the missing parts for 1.0.6.0 and found that there aren't any gaps there.

Here are notes that have a to-do.

- Create issue for top queries & investigate them, figure out how which page we want shown for a query https://github.com/btcpayserver/btcpayserver-doc/issues/628
- @dennisreimann Dennis will rebase Ricardo's PR https://github.com/btcpayserver/btcpayserver-doc/pull/768  
- https://github.com/btcpayserver/btcpayserver-doc/issues/created_by/Kukks - Ask @Kukks what this means

Besides those we talked about:
- Algolia search and lack of good algo it has.
- SMTP server and forgot password 
- How properly formatted issues are more likely to be tackled when they contain clear explanation of a problem and a to-do

**Comment by Zaxounette** [comment]
Thanks for the report, boss :)

**Comment by Zaxounette** [comment]
> https://github.com/btcpayserver/btcpayserver-doc/issues/created_by/Kukks - Ask Kukks what this means

@pavlenex , I can't recall, was this done ?
I'm looking through the doc-issues trying to find one I could tackle.
