### ISSUE TITLE
Twitter Spaces #2

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#43]
```meta
Date: 2021-07-07
Time: 7:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-07-07 19:00 UTC
```

### Agenda

Opening this issue so that we can determine the subject of our next Twitter Spaces Talk.

1. New Release?
2. Feel free to suggest the topic(s)

### Check your timezone

https://everytimezone.com/s/f7313cdb

### Join the call

TBA

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by pavlenex** [comment]
It's been suggested that the topic of the space is around 🇸🇻, so how about "Bitcoin Accepted Here - El Salvador Edition" where we can talk about ways local communities can prosper from BTCPay Server and talk about specific use-cases and ways in which people may use BTCPay to accept payments.

**Comment by dennisreimann** [comment]
This can be closed -- is a new Spaces session already in planning?

**Comment by Zaxounette** [comment]
Date is being defined.
