### ISSUE TITLE
Twitter Spaces #3

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#52]
```meta
Date: 2021-08-06
Time: 6:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-08-06 18:00 UTC
```

### Agenda

1. Continuing Discussion about "Bitcoin Accepted Here, El Salvador Edition" #43 

### To-do
1. Determine the list of guests
2. Ping previous guests 

### Check your timezone

https://everytimezone.com/s/244b39a2
### Join the call

LINK FOR CALL

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by dstrukt** [comment]
Glad to see we're trying this again!

**Comment by pavlenex** [comment]
Will probably have to re-schedule this one for the week after. We're in the mid of a release so lots of tasks prior to this one. cc @Zaxounette @rockstardev

**Comment by dstrukt** [comment]
Any update on the re-schedule?

**Comment by pavlenex** [comment]
Nothing yet, I've been swamped, if someone wants to take over Twitter Space organising, please let me know.
