### ISSUE TITLE
Community Call #0

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#7]
```meta
Date: 2020-12-05
Time: 6:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2020-12-05 18:00 UTC
```

### Agenda

BTCPay Server community call is a place for community to gather around, ask questions, discuss BTCPay, projcets their building on or simply ask for help on particular issues. Basically an AMA where we can all hang around once every two weeks and catch up on stuff. 

If you have a project being built on top of btcpay server, if you're a btcpay user and have feedback/questions or want to show us how you use BTCPay, feel free to let us know so that we can add you to the agenda.

1. Discussing the new direction of BTCPay Server (Plugin System)
2. Beginners Q and A
3. Discussing the new introductory video
4. Discussing the external integration support through our new API
5. TBD (Feel free to comment and suggest a topic) 

### Check your timezone

LINK FOR TIMEZONE https://everytimezone.com/s/54d44558

### Join the call

LINK FOR CALL https://meet.jit.si/btcpaycommunitycall

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by Kukks** [comment]
I'd also like to discuss external integration support, especially due to our new greenfield API capabilities. What it would take to rebuild some of them and replace usage of the shitty bitpay api

**Comment by prayank23** [comment]
I have 3 questions:

1. If there is a _WordPress_ website that plans to use _subscription_ based model for it's content, how can _btcpayserver_ be used in it to accept payments in **assets issued on Liquid**?

2. Didn't see any response to this issue however I think it's important to replace _username/password_ with _LN wallet/node_ in most of the Bitcoin projects: https://github.com/btcpayserver/btcpayserver/issues/2004

Also if someone can answer one related question on SE: https://bitcoin.stackexchange.com/questions/99584/can-we-use-lnurl-auth-to-create-a-better-password-manager

3. Do we have any **browser extensions associated with btcpayserver**? There was one related question on SE recently in which I can add more bitcoin projects: https://bitcoin.stackexchange.com/questions/100355/browser-wallet-btc-enabled/

**Comment by pavlenex** [comment]
Thanks everyone for hopping on the first community call. We had between 12-16 people through an hour long call.
There was no strict agenda as we wanted to get feedback from people, have fun and answer some questions.
Here are some notes I managed to catch:

- Discussing the plugin system
- How BTCPay Server evolved from reverse-engineered BitPay API UI to a payment platform.
- Discussing what frustrates people about the UI
- Discussing if people use internal wallet
- We got feedback from HRF representative Alex about the payment button CSS
- Zax mentioned we should look into how PayPal does buttons to avoid mess the CSS is causing for people's sites
- Patricia had some good insight on the UI
- J9 asked about privacy vulnerability in payment button, and we agreed we should disclose it in the next major release
- We answered some of the questions Prayank23 had and a few more from the chat.
