### ISSUE TITLE
Docs Call #5

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/organization#72]
```meta
Date: 2021-12-15
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-12-15 17:00 UTC
```

### Agenda

1. Talk about what docs we're want to prepare for the next release
2. Discuss starting a docs project where we can easier keep a track on tasks
3. Possibly set up this docs project on the meeting
4. Add/Discuss items that we want to accomplish in the longer term

### Check your timezone

https://everytimezone.com/s/24267725

### Join the call

[LINK FOR CALL](https://meet.jit.si/IAmHappyYouAreHappyWereAllHappy)

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by Zaxounette** [comment]
FYI, a last minute change makes me unavailable for this.

**Comment by britttttk** [comment]
Postponing this meeting by 1 week.

**Comment by dennisreimann** [comment]
Closed and reopened for the calendar file update
