### ISSUE TITLE
Zapier Demo Video Call #0

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/organization#73]
```meta
Date: 2021-12-04
Time: 7:30pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-12-04 19:30 UTC
```

### Agenda

1. Discuss Zapier Demo videos
- General "Getting started" video
- Few short "how to" videos, like "How to send an email when a BTCPay Invoice is paid". 
- We will use Zapier, the Invoice settled trigger and connect that to "Send an email" action.
- Later, we could do more advanced: "How to move 90% of my Bitcoin from my hot wallet into cold storage at the end of each day"

### Check your timezone

https://everytimezone.com/s/417b53c7

### Join the call

[LINK FOR CALL](https://meet.jit.si/IAmHappyYouAreHappyWereAllHappy)

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by woutersamaey** [comment]
This is a call to discuss how to move forward with some Zapier demo videos. What can we show to people, how to best do it, etc...

**Comment by woutersamaey** [comment]
Additionally we can also discuss how to get out of "beta". This involves creating some documentation and adding some samples to the account.

**Comment by britttttk** [comment]
Meeting Notes  - 💚 BTCPay + Zapier 🧡

- Everyone who has a Zapier account can use the BTCPay app right now
- You can sign up here for a free or paid account: https://zapier.com/
- Just search for BTCPay and click the integration popup and select it
- More Info: https://zapier.com/apps/btcpay-server/integrations


```
Creating Zaps
1. Create Zap, provide name, choose btcpay app (Beta)
2. Choose schedule if you want to use a built in trigger
3. Choose btcpay trigger event (select from one of the 7 webhooks)
4. It's store specific (account in Zapier)
```

Next Step:
- removing the beta label
- need 50+ users
- Construct a few examples of workflows/use cases (5 samples)
- Doc for better api permission
- Better permissions organization
- Once an api key is created, you cant modify api key, you need to create a new api key
- Really hard for debugging which permissions are needed
- Return missing permission error
- Webhook for when a new user is created, we don't have that yet, we only have store related activity for now
- Lightning monitor channels and do channel rebalancing or at least warn on low inbound liquidity (likely needs that functionality exposed by greenfield)
```

What should we show people? What would they be interested in?

Wouter:
0. send email, thanks for payment

Zax:
1. Liquidate payments with an exchange
- Likely none of the exchanges have Zapier, would need ot use api (just need to fill in the fields in the correct way and know a bit about apis, (advanced)). We can include it in the video, with a guide. For Kraken at least, it's possible. Unsure about Bitfinex
2. Auto move to cold storage

All 3 are possible today.

**Comment by britttttk** [comment]
Some API ideas/improvements discussed related to this effort:
cc @Kukks @bolatovumar @dennisreimann
